config/routes.rb
Rails.application.routes.draw do

  

  ##### DASHBOARD ######
  get "dashboard", to:'dashboard#index'
  get "dashboard-setup", to:"dashboard#home"
  get "dashboard-membres", to:"dashboard#members"
  get "dashboard-articles", to:"dashboard#articles"
  get "dashboard-campagnes", to:"dashboard#campagnes"
  get "dashboard-projets", to:"dashboard#projets"
  get "dashboard-adhesions", to:"dashboard#bememberships"
  get "dashboard-benevols", to:"dashboard#benevols"

  ##### USER ######
   devise_scope :user do
    get 'action-plus-sign-up-member', to:'bememberships#users' #Member's Account
    get 'action-plus-sign-in', to: 'devise/sessions#new'
    get 'action-plus-sign-up', to: 'devise/registrations#new', as: "new_user_registration"
    get 'profile/edit'    => 'devise/registrations#edit'
    get 'profile/cancel'  => 'devise/registrations#cancel'
    delete 'sign-out', to: 'devise/sessions#destroy'
  end

  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  #Add UUID ORDER
  self.implicit_order_column = "created_at"


  scope :dashboard, -> { all.order('created_at desc')}
  scope :lastSigned, -> {all.order('last_sign_in_at desc')}

  # Ex:- scope :active, -> {where(:active => true)}
  scope :membership, -> { where("category = ?", "Adherent" || "organisation").order('created_at desc')}
  scope :monthlyActif, ->  { where(:created_at => (Time.now.midnight - 30.day)..Time.now.midnight)}
  scope :weeklyActif, ->  { where(:created_at => (Time.now.midnight - 7.day)..Time.now.midnight)}
  # Ex:- scope :active, {where(:active => true)}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable


  has_one_attached :avatar
  
  STATUS= ["Editeur", "Level 2", "Level 3"]

  def full_name
    "#{self.first_name} #{self.last_name}" 
  end

  validates :first_name, :last_name, :full_name, :email, :password,
              :status, :country, :full_contact, presence: true
    
   validates :full_name,presence: true,
              format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ },
              length: { minimum:5, maximum: 30,
              message: "%{value} verifier votre nom complet"}

                

   ################## SLUG ###############
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  
  def should_generate_new_friendly_id?
    full_name_changed?
  end 
 
  
  ################## BEFORE SAVE  #########
  before_save do
    #self.country            = country.strip.squeeze(" ")
    self.full_contact            = full_contact .strip.squeeze(" ").capitalize
    self.first_name         = first_name.strip.squeeze(" ").downcase.capitalize
    self.last_name          = last_name.strip.squeeze(" ").downcase.capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    
    protected
    # If you have extra params to permit, append them to the sanitizer.
    def configure_permitted_parameters
        sign_up_params = [ :first_name, :last_name, :full_name, :status,
                        :country, :email, :avatar, :password, :slug,
                            :gender, :full_contact]
            
        #Devise strong Params
        devise_parameter_sanitizer.permit :sign_up, keys: sign_up_params
        devise_parameter_sanitizer.permit :account_update, keys: sign_up_params
        devise_parameter_sanitizer.permit :sign_in, keys: [:email, :password]
    end

    def after_sign_in_path_for(resource)
        dashboard_path
    end

    def after_sign_up_path_for(resource)
        dashboard_path
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @MembersList = Bemembership.dashboard
    @ProjetsList = Projet.dashboard
    @CampagnesList = Campagne.dashboard
    @LastSigned = User.lastSigned
  end

  def home
  end

  def members
    @MembersList = Bemembership.dashboard
    @MembersMonthly = @MembersList.monthlyActif
    @MembersWeekly = @MembersMonthly.weeklyActif
  end

  def articles
    @Articles = Article.dashboard
    @ArticlesMonthly = @Articles.monthlyActif
    @ArticlesWeekly = @ArticlesMonthly.weeklyActif
  end
    
  def campagnes
    @Campagnes = Campagne.dashboard
    @CampMonthly = @Campagnes.monthlyActif
    @CampWeekly = @CampMonthly.weeklyActif
  end

  def projets
    @Projets = Projet.dashboard
    @ProjetsMonthly = @Projets.monthlyActif
    @ProjetsWeekly = @ProjetsMonthly.weeklyActif
  end

  def bememberships
    
  end
  def benevols
    @Benevols = Benevol.dashboard
    @BenevolsMonthly = @Benevols.monthlyActif
    @BenevolsWeekly = @BenevolsMonthly.weeklyActif

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    #Add layouts content
    def title
    base_title = "Action+  Missions humanitaires"
    if @title.nil?
    base_title
    else
    "#{@title} | #{base_title}"
    end
    end

    #site description
    def description
    "Action+ ......"
    end

    def keywords
    "Faire un don, don, association, ong, donner, don en ligne, don sécurisé, soutenir, donation, make a donation"
    end

    #Sign in and up anywhere on app
    def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def resource_class
    User
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  #USER NOTICE
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
end


    # Notification
def render_notification
    render "layouts/flash"
 end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/dashboard/articles.html.erb
<h1>Dashboard#articles</h1>
<p>Find me in app/views/dashboard/articles.html.erb</p>

app/views/dashboard/bememberships.html.erb
<h1>Dashboard#bememberships</h1>
<p>Find me in app/views/dashboard/bememberships.html.erb</p>

app/views/dashboard/benevols.html.erb
<h1>Dashboard#benevols</h1>
<p>Find me in app/views/dashboard/benevols.html.erb</p>

app/views/dashboard/campagnes.html.erb
<h1>Dashboard#campagnes</h1>
<p>Find me in app/views/dashboard/campagnes.html.erb</p>

app/views/dashboard/home.html.erb
<h1>Dashboard#home</h1>
<p>Find me in app/views/dashboard/home.html.erb</p>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/dashboard/members.html.erb
<h1>Dashboard#members</h1>
<p>Find me in app/views/dashboard/members.html.erb</p>

app/views/dashboard/projets.html.erb
<h1>Dashboard#projets</h1>
<p>Find me in app/views/dashboard/projets.html.erb</p>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message" data-controller="removals" data-action="animationend->removals#remove">
    <%= message %>
  </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="description" content="<%= description %>">
    <meta name="keywords" content="<%= keywords %>">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <!-- CDN-->
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.38.1/dist/full.css" rel="stylesheet" type="text/css"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/flowbite@1.3.3/dist/flowbite.js"></script>
    <%= render "shared/layouts/header" %>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/blog/">

    <!-- Favicon-->
    <%= favicon_link_tag asset_path('logo/flavico-action.png') %>

    <!-- Analytics-->
    <%= render "shared/analytics/analytics" %>

  </head>

  <body>
  <style type="text/css">
      @media only screen and(min-width: 1025px) {
          .hero--video-donate-form {
              --hero_text_color: #fff;
              --hero_bg_color: #000;
          }

          .hero--video-overlay {
              --hero_bg_color: #000;
          }
      }
  </style>

    <%= yield %>

  <!--Footer  -->
  <%= render "shared/layouts/footer" %>

  </body>
</html>

app/views/shared/analytics/_analytics.html.erb
<!--Clarity screen -->
<!--Clarity :: Page d'accueil -->

<script type="text/javascript">
    ( function ( c, l, a, r, i, t, y ) {

        c[ a ] = c[ a ] || function () {

            ( c[ a ].q = c[ a ].q || [] ).push( arguments );

        };
        t = l.createElement( r );
        t.async = 1;
        t.src = "https://www.clarity.ms/tag/" + i;
        y = l.getElementsByTagName( r )[ 0 ];
        y.parentNode.insertBefore( t, y );

    } )( window, document, "clarity", "script", "dvs2x6wt02" );
</script>

<!--Clarity :: Page d'accueil -->

app/views/shared/flash/_notices.html.erb
  <% flash.each do |type, msg| %>
    <div class="toast alert-<%= bootstrap_class_for_flash(type) %>" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <strong class="mr-auto">vous etes</strong>
        <small>Maintenant</small>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body">
        <%= msg %>
      </div>
    </div>
  <% end %> 

app/views/welcome/shared/_articles.html.erb
<!-- ======= Gallery Section ======= -->
    <section id="gallery" class="gallery">

      <div class="container" data-aos="fade-up">
        
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
          <h2 class="section-title text-center font-bold text-4xl px-3">Actualités</h2>      
        </div>
      </div>

      <div class="container-fluid" data-aos="fade-up" data-aos-delay="100">
        <div class="row g-0">
        
          <% @HomeArticles.each do |homeArticle| %>
            <div class="col-lg-3 col-md-4">
              <div class="gallery-item">
                <%= link_to article_path(homeArticle), class:"gallery-lightbox" do %>
                <% if homeArticle.heroImg.attached? %>
                  <%= image_tag(homeArticle.heroImg, class:"img-fluid") %>
                  <% else %>
                    <%= image_tag "media/2.jpeg", class:"img-fluid", alt:"" %>
                <% end %>
                <% end %>
              </div>
            </div>
            
          <% end %>
        </div>
      </div>
    </section><!-- End Gallery Section -->

app/views/welcome/shared/_donnez.html.erb
        <%= render "welcome/shared/dons/form" %>  

app/views/welcome/shared/_hheader.html.erb
<!-- Top Bar -->
<%= render "welcome/shared/top_bar" %>
<!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-cente bg-white py-2 uppercase text-4xl">
  
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">
      <h1 class="logo me-auto me-lg-0">
        <%= link_to root_path do %> <%= image_tag 'logo/logo-action.png', alt:"logo action+", class:"bg-gray-100 h-12 w-10 rounded-full " %><% end %>
      </h1>
      <nav id="navbar" class="navbar order-last order-lg-0 font-semibold">
      
        <ul class="text-6xl">
          <li><%= link_to 'Accueil', root_path , class:"nav-link scrollto active " %></li>
          <li><%= link_to 'Nous Découvrir', "mot-fondateur", class:"nav-link scrollto" %></li>
          <li><%= link_to 'Nous Aider', "nos-campagnes-financements", class:"nav-link scrollto" %></li>
          <li><%= link_to 'Actualités', "nos-articles", class:"nav-link scrollto" %></li>
          <li><%= link_to "Agissons Ensemble", "agisons-ensemble", class:"nav-link scrollto" %></li> 
          <li><%#= link_to "Agissons Ensemble" agir_path, class:"nav-link scrollto" %></li>
          <li class="dropdown"><a href="#"><span>En Action</span> <i class="dropdown-toggle"></i></a>
            <ul>
              <li><a href="<%= root_path %>#eau-potable">EAUX POTABLE</a></li>
              <li><a href="<%= root_path %>#electricite">ELECTRICITÉ</a></li>
              <li><a href="<%= root_path %>#education">EDUCATION</a></li>
            </ul>
          </li>         
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
     
      <%= link_to  adhesion_path, class:"btn-book animated fadeInUp 
            text-white bg-red-500 hover:bg-red-400 focus:outline
              focus:ring-red-300 font-bold rounded-b-xl rounded-tr-xl text-xl px-5
              py-2.5 text-center mr-2 mb-2" do %>
        <span class="">Adhérer</span>
      <% end %>
    </div>
  </header><!-- End Header -->

app/views/welcome/shared/_projets.html.erb
<!-- ======= Events Section ======= -->
    <section id="projets-soutenir" class="events">
      <div class="container" data-aos="fade-up">

        
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
          <h2 class="section-title text-center text-white font-bold text-4xl px-3">Donnez pour soutenir nos actions</h2>      
        </div>

        <div class="events-slider swiper-container" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">

            
            <% @HomeProjets.each do |homeProjet| %>
            <div class="swiper-slide">    
              <div class="row event-item">
                <div class="col-lg-6">
                 <% if homeProjet.heroImg.attached? %>
                   <%= image_tag(homeProjet.heroImg, class:"img-fluid") %>
                  <% else %>
                   <%= image_tag "media/1.jpeg", class:"img-fluid", alt:"" %>
                 <% end %>
                </div>
                <div class="col-lg-6 pt-4 pt-lg-0 content">
                  <h3 class="text-white"> <%= homeProjet.title %></h3>
                  <div class="price ">
                    <p><span>Objectif: <%= homeProjet.amount %></span></p>
                  </div>
                  <div class=" mb-4">
                    <%= link_to projet_path(homeProjet), class:"hover:text-white text-white no-underline" do %>
                      <%= truncate(strip_tags(homeProjet.content.to_s.html_safe), length: 600)%>
                      <span class=" text-red-500 " id=start-reading><i class="mx-2">Découvrez plus >> </i></span>
                    <% end %>
                  </div>
                                 
                  <button type="button" class="btn-book animated fadeInUp 
                          scrollto text-white bg-red-500 hover:bg-red-400 focus:outline
                          focus:ring-4 focus:ring-red-300 font-bold rounded-b-xl rounded-tr-xl text-xl px-5
                            py-2.5 text-center mr-2 mb-2 uppercase" data-bs-toggle="modal" data-bs-target="#First-staticBackdrop">
                                    je fais un don
                  </button>
                  
                </div>
              </div>
            </div><!-- End testimonial item -->
              <!-- Modal 1-->
              <div class="modal fade" id="First-staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="First-staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title font-bold" id="staticBackdropLabel"><span class="underline">Soutenir :</span> <%= homeProjet.title %></h5>
                      <button type="button" class="btn bg-gray-400 btn-secondary" data-bs-dismiss="modal">
                      Fermer
                      </button>
                    </div>
                    <div class="modal-body">
                      <div role="alert" class="container mx-auto md:w-full max-w-lg">
                        <div class="relative py-8 px-2 md:px-10 bg-white shadow-md rounded border border-gray-400">
                        
                          <h1 class="text-gray-800 font-lg font-bold tracking-normal leading-tight mb-4">Informations de Dons</h1>
                            <label for="name" class="text-gray-800 text-sm font-bold leading-tight tracking-normal">Nom Complet</label>
                            <input id="name" class="mb-3 mt-2 text-gray-600 focus:outline-none focus:border focus:border-indigo-700 
                            font-normal w-full h-10 flex items-center pl-3 text-sm border-gray-300 rounded border" placeholder="Konan James" />
                            
                            <label for="email2" class="text-gray-800 text-sm font-bold leading-tight tracking-normal">N° de la Carte</label>
                            <div class="relative mb-3 mt-2">
                              <div class="absolute text-gray-600 flex items-center px-4 border-r h-full">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-credit-card" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                  <path stroke="none" d="M0 0h24v24H0z" />
                                  <rect x="3" y="5" width="18" height="14" rx="3" />
                                  <line x1="3" y1="10" x2="21" y2="10" />
                                  <line x1="7" y1="15" x2="7.01" y2="15" />
                                  <line x1="11" y1="15" x2="13" y2="15" />
                                </svg>
                              </div>
                              <input id="email2" class="text-gray-600 focus:outline-none focus:border focus:border-indigo-700 font-normal w-full h-10 flex items-center pl-16 text-sm border-gray-300 rounded border" placeholder="XXXX - XXXX - XXXX - XXXX" />
                            </div>
                            <label for="expiry" class="text-gray-800 text-sm font-bold leading-tight tracking-normal">Date D'Expiration</label>
                            <div class="relative mb-3 mt-2">
                              <div class="absolute right-0 text-gray-600 flex items-center pr-3 h-full cursor-pointer">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-event" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                  <path stroke="none" d="M0 0h24v24H0z" />
                                  <rect x="4" y="5" width="16" height="16" rx="2" />
                                  <line x1="16" y1="3" x2="16" y2="7" />
                                  <line x1="8" y1="3" x2="8" y2="7" />
                                  <line x1="4" y1="11" x2="20" y2="11" />
                                  <rect x="8" y="15" width="2" height="2" />
                                </svg>
                              </div>
                              <input id="expiry" class="text-gray-600 focus:outline-none focus:border focus:border-indigo-700 font-normal w-full h-10 flex items-center pl-3 text-sm border-gray-300 rounded border" placeholder="MM/YY" />
                            </div>
                            <label for="cvc" class="text-gray-800 text-sm font-bold leading-tight tracking-normal">CVC</label>
                            <div class="relative mb-5 mt-2">
                              <div class="absolute right-0 text-gray-600 flex items-center pr-3 h-full cursor-pointer">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-info-circle" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                  <path stroke="none" d="M0 0h24v24H0z"></path>
                                    <circle cx="12" cy="12" r="9"></circle>
                                    <line x1="12" y1="8" x2="12.01" y2="8"></line>
                                    <polyline points="11 12 12 12 12 16 13 16"></polyline>
                                </svg>
                              </div>
                              <input id="cvc" class="mb-8 text-gray-600 focus:outline-none focus:border focus:border-indigo-700 font-normal w-full h-10 flex items-center pl-3 text-sm border-gray-300 rounded border" placeholder="MM/YY" />
                            
                            </div>
                            <div class="relative mb-5 mt-2">
                            <label class="text-gray-800 text-sm font-bold leading-tight tracking-normal">Montant du Don</label><hr class="mb-3">
                            <div class="form-check form-check-inline">
                              <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                              <label class="form-check-label" for="inlineRadio1">10$</label>
                            </div>
                            <div class="form-check form-check-inline">
                              <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2" checked >
                              <label class="form-check-label" for="inlineRadio2">20$</label>
                            </div>
                            <div class="form-check form-check-inline">
                              <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3" >
                              <label class="form-check-label" for="inlineRadio3">50$</label>
                            </div>

                              <input class="mb-8 text-gray-600 focus:outline-none focus:border focus:border-indigo-700 font-normal w-full h-10 flex items-center pl-3 text-sm border-gray-300 rounded border" placeholder="Autres montant" />
                            
                            </div>
                            <!--
                            <div class="flex items-center justify-start w-full">
                                <button class="focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-700
                                transition duration-150 ease-in-out hover:bg-green-600 bg-green-700 rounded
                                text-white px-8 py-2 text-sm">Don Mensuel</button>
                                <button class="focus:outline-none focus:ring-2 focus:ring-offset-2  focus:ring-gray-400 ml-3
                                bg-gray-300 transition duration-150 text-gray-600 ease-in-out hover:border-gray-400
                                  hover:bg-gray-300 border rounded px-8 py-2 text-sm" >Une Fois</button>
                            </div>
                            -->
                            <button class="cursor-pointer absolute top-0 right-0 mt-4 mr-5 text-gray-400 hover:text-gray-600 transition duration-150 ease-in-out rounded focus:ring-2 focus:outline-none focus:ring-gray-600" onclick="modalHandler()" aria-label="close modal" role="button">
                                <svg  xmlns="http://www.w3.org/2000/svg"  class="icon icon-tabler icon-tabler-x" width="20" height="20" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" />
                                    <line x1="18" y1="6" x2="6" y2="18" />
                                    <line x1="6" y1="6" x2="18" y2="18" />
                                </svg>
                            </button>
                          </div>

                        
                        </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn bg-red-500 text-white font-semibold uppercase">Confirmez votre Don</button>

                    </div>
                  </div>
                </div>
              </div>
           
            <% end %>
            

          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Events Section -->

app/views/welcome/shared/_terrain.html.erb
<!-- ======= Specials Section ======= -->
    <section id="specials" class="specials">
      <div class="container" data-aos="fade-up">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
          <h2 class="section-title text-center font-bold text-4xl px-3">Action<sup>+</sup> sur le Terrain</h2>      
        </div>
        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <% @HomeCampagnes.each do |homeCamp| %>
            <div class="col-lg-3">
              <ul class="nav nav-tabs flex-column">
                <li class="nav-item bg-blue-200">
                  <a class="nav-link active show  bg-blue-200 hover:bg-blue-400"
                   data-bs-toggle="<%= homeCamp.title %>" href="#<%= homeCamp.title %>">
                  <span class="font-bold"><%= homeCamp.title %></span> 
                  </a>
                </li>
              </ul>
            </div>
            <div class="col-lg-9 mt-4 mt-lg-0">
              <div class="tab-content">
                <div class="tab-pane active show" id="<%= homeCamp.title %>">
                  <div class="row">
                    <div class="col-lg-8 details order-2 order-lg-1">
                      <div class="">
                        <%= link_to campagne_path(homeCamp), class:"hover:text-black text-black no-underline" do %>
                            <%= truncate(strip_tags(homeCamp.content.to_s.html_safe), length: 400)%>
                            <span class="text-red-500" id=start-reading><i class="mx-2">Lire plus >> </i></span>
                        <% end %>
                      </div>
                    </div>
                    <div class="col-lg-4 text-center order-1 order-lg-2">
                      <% if homeCamp.heroImg.attached? %>
                        <%= image_tag(homeCamp.heroImg, alt:"", class:"img-fluid") %>
                      <% else %>
                        <%= image_tag "media/5.jpeg", alt:"", class:"img-fluid"%>
                      <% end %>
                    </div>
                  </div>
                </div>
                
              </div>
            </div>
          <% end %>
        </div>

      </div>
    </section><!-- End Specials Section -->